In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
#scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()`

In [4]:
scalar.ndim

0

In [5]:
# get tensor back as Python int
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX[1]

tensor([ 9, 10])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
# tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([1, 4, 3])

In [13]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

## Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors ful of random numbers and then adjust tnose random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [14]:
random_tensor = torch.rand(3, 2)
random_tensor

tensor([[0.7852, 0.7186],
        [0.6046, 0.6680],
        [0.4200, 0.5813]])

In [15]:
random_image_size_tensor = torch.rand(size=(5,10,10))
random_image_size_tensor

tensor([[[0.8849, 0.0765, 0.0113, 0.3023, 0.5851, 0.0747, 0.0816, 0.6373,
          0.3180, 0.3304],
         [0.5147, 0.9759, 0.8302, 0.6936, 0.8955, 0.1823, 0.7187, 0.3525,
          0.4199, 0.4459],
         [0.4317, 0.6712, 0.6239, 0.0217, 0.6664, 0.8714, 0.7806, 0.6490,
          0.8438, 0.8944],
         [0.3469, 0.7297, 0.2735, 0.7582, 0.2943, 0.6631, 0.0541, 0.7953,
          0.4233, 0.7899],
         [0.4664, 0.9556, 0.5691, 0.7591, 0.2225, 0.2541, 0.4868, 0.1348,
          0.1728, 0.2249],
         [0.3418, 0.6750, 0.0302, 0.1205, 0.2843, 0.6657, 0.7936, 0.7754,
          0.3756, 0.5736],
         [0.0259, 0.0613, 0.7092, 0.4984, 0.5675, 0.4882, 0.0204, 0.5318,
          0.9713, 0.3276],
         [0.8532, 0.7147, 0.0154, 0.3804, 0.1349, 0.4866, 0.5992, 0.1692,
          0.8874, 0.3175],
         [0.5085, 0.7116, 0.1214, 0.4783, 0.1299, 0.2763, 0.5904, 0.2963,
          0.3009, 0.0574],
         [0.9146, 0.3484, 0.1312, 0.3762, 0.8647, 0.3552, 0.1281, 0.9557,
          0.1567,

In [16]:
#create a tensor with all zeroes
zeroes = torch.zeros(size=(3,4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
#create a tensor with all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [19]:
one_to_ten = torch.arange(start=0, end=10, step=1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0875, 0.5864, 0.1330, 0.1509],
        [0.1909, 0.4477, 0.3149, 0.5273],
        [0.0997, 0.0467, 0.6257, 0.1868]])

In [22]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.0875, 0.5864, 0.1330, 0.1509],
        [0.1909, 0.4477, 0.3149, 0.5273],
        [0.0997, 0.0467, 0.6257, 0.1868]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [23]:
# create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [24]:
# Multiply by 10
tensor * 10

tensor([10, 20, 30])

In [25]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [26]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

two main ways of preforming multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy. 
1. The **inner dimensions** must match:
// @ stands for matrix multiplication
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work


In [27]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [28]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [29]:
tensor

tensor([1, 2, 3])

In [30]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [31]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.53 ms, sys: 248 µs, total: 1.77 ms
Wall time: 8.13 ms


In [32]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 205 µs, sys: 0 ns, total: 205 µs
Wall time: 159 µs


tensor(14)

In [33]:
### One of the most common errors in deep learning: is shape errors
tensor_A = torch.tensor([[1,2], [3,4], [5,6]])
tensor_B = torch.tensor([[7,10], [8,11], [9, 12]])
torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul.



RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

to fix the tensor shape error, we can manipulate the shape of our tensors using transpose

a **transpose** switches the axes or dimensions of a given tensor

In [34]:
tensor_A.shape

torch.Size([3, 2])

In [36]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [37]:
tensor_B, tensor_B.T.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([2, 3]))

### Finding the min, max, mean, sum, ect (tensor aggregation)


In [38]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [40]:
#find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [41]:
#find the mean - torch.mean() function requires a tensor of float32 
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [42]:
#Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [43]:
# Find the position in tenosor that has the minimum value with argmin() returns index position of target tensor were the minimum value occurs
x.argmin()

tensor(0)

In [44]:
x[0]

tensor(0)

In [45]:
# find the position in the tensor that has the maximum value with argmax() 
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way


In [46]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [47]:
# add an extra dimension
x_reshaped = x.reshape(1,9) 
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [54]:
X_stacked = torch.stack([x, x, x, x], dim=1)
X_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [55]:
# Stack the tensors on top of each other
X_stacked[0][0] = 2.
X_stacked

tensor([[2., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [59]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = torch.squeeze(x_reshaped)
print(f"Squeezed tensor: {x_squeezed}")
print(f"Squeezed shape: {x_squeezed.shape}")


Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])
Squeezed tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Squeezed shape: torch.Size([9])


In [60]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze()
x_unsqueezed = torch.unsqueeze(x_squeezed, dim=0)
print(f"Unsqueezed tensor: {x_unsqueezed}")
print(f"Unsqueezed shape: {x_unsqueezed.shape}")


Previous target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
Unsqueezed tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Unsqueezed shape: torch.Size([1, 9])


In [69]:
# torch.permute - rearranges the dimensions of the target tensor
x_original = torch.rand(size=(224, 224, 3)) # [height, width, channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.clone().detach().permute(2, 0, 1) # [channels, height, width]
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [70]:
print(f"{x_original[0, 0, 0]} and {x_permuted[0, 0, 0]}")
x_original[0, 0, 0] = 1.
print(f"{x_original[0, 0, 0]} and {x_permuted[0, 0, 0]}")

0.8908745050430298 and 0.8908745050430298
1.0 and 0.8908745050430298


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy. 

In [71]:
#create a tensor
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [72]:
#lets index on the new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [73]:
#lets index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [74]:
#lets index on the most inner bracket (dim=2)
x[0][0][0]

tensor(1)

In [75]:
# you can use : to select all of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [76]:
# get all values of 0th and 1st dimensions but only index 2 of the 2nd dimension
x[:, :, 2]

tensor([[3, 6, 9]])

In [79]:
# get all values of the 0th dimension but only the 1 index value of the 1st and 2nd dimensions
x[:, 1, 1]

tensor([5])

In [80]:
# get index 0 of 0th and 1st dimension and all values of the 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [82]:
#Index on x to return 9
x[0, 2, 2]

#Index on x to return 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])

## PyTorch tensors and NumPy

NumPy is a popular scientific python numerical computing library. 

because of this, PyTorch has functionality to interact with it. 

* Data in  NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [88]:
#NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning, when converting from numpy to pytorch. Pytorch reflects numpy's default data type of float64 unless otherwise specified.
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [89]:
#change the value of array, what will this do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [90]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [91]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavor" the randomness.


In [97]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0343, 0.5219, 0.6714, 0.3202],
        [0.0520, 0.5426, 0.8707, 0.2362],
        [0.6460, 0.1370, 0.1854, 0.3756]])
tensor([[0.1047, 0.6746, 0.3582, 0.9834],
        [0.3040, 0.9458, 0.9787, 0.2299],
        [0.7712, 0.0128, 0.8977, 0.5978]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [101]:
# lets make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) # must be called each time you want to reset the random seed.
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on GPU's (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good). 

### Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU-  takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options. 


In [102]:
!nvidia-smi

Mon Dec 12 17:13:44 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.86.01    Driver Version: 515.86.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:03:00.0 Off |                  N/A |
|  0%   30C    P8     9W / 250W |      9MiB / 11264MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:06:00.0  On |                  N/A |
|  0%   

In [103]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to set up device agnostic code
E.g. run on GPU if available, else default to CPU

In [104]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [105]:
# Count number of devices
torch.cuda.device_count()

2

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [106]:
# create a tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

#Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [107]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving Tensors back to the CPU

In [108]:
# If tensor is on GPU, can transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [109]:
# to fix GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [110]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')