In [1]:
import torch
torch.cuda.is_available()

True

In [2]:
#scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()`

In [3]:
scalar.ndim

0

In [4]:
# get tensor back as Python int
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX[1]

tensor([ 9, 10])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 4, 3])

In [14]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

## Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors ful of random numbers and then adjust tnose random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [15]:
random_tensor = torch.rand(3, 2)
random_tensor

tensor([[0.2974, 0.8367],
        [0.8673, 0.6428],
        [0.9319, 0.7808]])

In [18]:
random_image_size_tensor = torch.rand(size=(5,10,10))
random_image_size_tensor

tensor([[[0.9851, 0.6932, 0.0843, 0.7914, 0.6313, 0.3161, 0.8025, 0.8061,
          0.2766, 0.4630],
         [0.5901, 0.4862, 0.6061, 0.8138, 0.3566, 0.6614, 0.4989, 0.5741,
          0.2724, 0.1814],
         [0.1923, 0.4660, 0.1213, 0.3897, 0.8536, 0.8807, 0.1493, 0.5257,
          0.3772, 0.6492],
         [0.6591, 0.7065, 0.2799, 0.6244, 0.6783, 0.2366, 0.6470, 0.2832,
          0.7213, 0.5266],
         [0.7359, 0.0574, 0.9863, 0.8883, 0.0651, 0.9636, 0.2695, 0.7391,
          0.6694, 0.1228],
         [0.2467, 0.6270, 0.8938, 0.4544, 0.2554, 0.8633, 0.2650, 0.1738,
          0.2590, 0.6604],
         [0.5554, 0.9064, 0.2168, 0.5318, 0.4960, 0.4005, 0.9727, 0.8930,
          0.7803, 0.7995],
         [0.3514, 0.0581, 0.1908, 0.5450, 0.9723, 0.0625, 0.6364, 0.6035,
          0.6739, 0.5398],
         [0.9438, 0.5654, 0.2431, 0.3987, 0.3413, 0.1459, 0.6341, 0.9280,
          0.7773, 0.1596],
         [0.6397, 0.9972, 0.7268, 0.5723, 0.1987, 0.7719, 0.6607, 0.2163,
          0.8679,

In [20]:
#create a tensor with all zeroes
zeroes = torch.zeros(size=(3,4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
#create a tensor with all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [30]:
one_to_ten = torch.arange(start=0, end=10, step=1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7525, 0.2643, 0.2801, 0.2858],
        [0.6007, 0.1972, 0.9083, 0.3889],
        [0.8143, 0.2455, 0.6949, 0.1904]])

In [34]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.7525, 0.2643, 0.2801, 0.2858],
        [0.6007, 0.1972, 0.9083, 0.3889],
        [0.8143, 0.2455, 0.6949, 0.1904]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [35]:
# create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [36]:
# Multiply by 10
tensor * 10

tensor([10, 20, 30])

In [37]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [39]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

two main ways of preforming multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy. 
1. The **inner dimensions** must match:
// @ stands for matrix multiplication
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work


In [42]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [43]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [44]:
tensor

tensor([1, 2, 3])

In [45]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [46]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.75 ms, sys: 38 µs, total: 1.79 ms
Wall time: 40.6 ms


In [47]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 288 µs, sys: 0 ns, total: 288 µs
Wall time: 176 µs


tensor(14)

In [ ]:
### One of the most common errors in deep learning: is shape errors
tensor_A = torch.tensor([1,2], [3,4], [5,6])
